name: Linting & Unit testing with code coverage Validation

on:
  push:
    branches:
      - master
      - release
      - sit-release
  pull_request:
    branches:
      - master
      - release
      - sit-release

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linting & Unit testing with code coverage testing
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing NPM packages
        run: npm install
      - name: Lint & Standards Validation
        run: npm run test
      - name: Unit Testing
        run: npm run test
      - name: Code Coverage
        run: npm run test
